import type {App, Plugin} from 'vue';
import {VueAvatar} from './components/VueAvatar';
import {VueBadge} from './components/VueBadge';
import {VueButton} from './components/VueButton';
import {VueCheckbox} from './components/VueCheckbox';
import {VueComboBox} from './components/VueComboBox';
import {VueDialog} from './components/VueDialog';
import {VueDivider} from './components/VueDivider';
import {VueDropZone} from './components/VueDropZone';
import {VueFlex} from './components/VueFlex';
import {VueForm} from './components/VueForm';
import {VueGrid} from './components/VueGrid';
import {VueIcon, VueIllustration, VueUIIcon} from './components/VueIcon';
import {VueIllustratedMessage} from './components/VueIllustratedMessage';
import {VueImage} from './components/VueImage';
import {VueInlineAlert} from './components/VueInlineAlert';
import {VueLabel} from './components/VueLabel';
import {VueLabeledValue} from './components/VueLabeledValue';
import {VueLink} from './components/VueLink';
import {VueListBox} from './components/VueListBox';
import {VueMenu} from './components/VueMenu';
import {VueMeter} from './components/VueMeter';
import {VueNumberField} from './components/VueNumberField';
import {VuePopover} from './components/VuePopover';
import {VueProgressBar} from './components/VueProgressBar';
import {VueRadio, VueRadioGroup} from './components/VueRadioGroup';
import {VueSearchField} from './components/VueSearchField';
import {VueSlider} from './components/VueSlider';
import {VueSpectrumProvider} from './components/VueSpectrumProvider';
import {VueStatusLight} from './components/VueStatusLight';
import {VueSwitch} from './components/VueSwitch';
import {VueTable} from './components/VueTable';
import {VueText} from './components/VueText';
import {VueTextField} from './components/VueTextField';
import {VueTree} from './components/VueTree';
import {VueView} from './components/VueView';
import {VueWell} from './components/VueWell';

export const VueSpectrumPlugin: Plugin = {
  install(app: App) {
    app.component(VueSpectrumProvider.name ?? 'VueSpectrumProvider', VueSpectrumProvider);
    app.component(VueAvatar.name ?? 'VueAvatar', VueAvatar);
    app.component(VueBadge.name ?? 'VueBadge', VueBadge);
    app.component(VueButton.name ?? 'VueButton', VueButton);
    app.component(VueCheckbox.name ?? 'VueCheckbox', VueCheckbox);
    app.component(VueComboBox.name ?? 'VueComboBox', VueComboBox);
    app.component(VueDialog.name ?? 'VueDialog', VueDialog);
    app.component(VueDivider.name ?? 'VueDivider', VueDivider);
    app.component(VueDropZone.name ?? 'VueDropZone', VueDropZone);
    app.component(VueFlex.name ?? 'VueFlex', VueFlex);
    app.component(VueForm.name ?? 'VueForm', VueForm);
    app.component(VueGrid.name ?? 'VueGrid', VueGrid);
    app.component(VueIcon.name ?? 'VueIcon', VueIcon);
    app.component(VueUIIcon.name ?? 'VueUIIcon', VueUIIcon);
    app.component(VueIllustration.name ?? 'VueIllustration', VueIllustration);
    app.component(VueIllustratedMessage.name ?? 'VueIllustratedMessage', VueIllustratedMessage);
    app.component(VueImage.name ?? 'VueImage', VueImage);
    app.component(VueInlineAlert.name ?? 'VueInlineAlert', VueInlineAlert);
    app.component(VueLabel.name ?? 'VueLabel', VueLabel);
    app.component(VueLabeledValue.name ?? 'VueLabeledValue', VueLabeledValue);
    app.component(VueLink.name ?? 'VueLink', VueLink);
    app.component(VueListBox.name ?? 'VueListBox', VueListBox);
    app.component(VueMeter.name ?? 'VueMeter', VueMeter);
    app.component(VueMenu.name ?? 'VueMenu', VueMenu);
    app.component(VueNumberField.name ?? 'VueNumberField', VueNumberField);
    app.component(VuePopover.name ?? 'VuePopover', VuePopover);
    app.component(VueProgressBar.name ?? 'VueProgressBar', VueProgressBar);
    app.component(VueRadioGroup.name ?? 'VueRadioGroup', VueRadioGroup);
    app.component(VueRadio.name ?? 'VueRadio', VueRadio);
    app.component(VueSearchField.name ?? 'VueSearchField', VueSearchField);
    app.component(VueSlider.name ?? 'VueSlider', VueSlider);
    app.component(VueStatusLight.name ?? 'VueStatusLight', VueStatusLight);
    app.component(VueSwitch.name ?? 'VueSwitch', VueSwitch);
    app.component(VueTable.name ?? 'VueTable', VueTable);
    app.component(VueText.name ?? 'VueText', VueText);
    app.component(VueTextField.name ?? 'VueTextField', VueTextField);
    app.component(VueTree.name ?? 'VueTree', VueTree);
    app.component(VueView.name ?? 'VueView', VueView);
    app.component(VueWell.name ?? 'VueWell', VueWell);
  }
};

export {VueAvatar, VueBadge, VueButton, VueCheckbox, VueComboBox, VueDialog, VueDivider, VueDropZone, VueFlex, VueForm, VueGrid, VueIcon, VueIllustration, VueIllustratedMessage, VueImage, VueInlineAlert, VueLabel, VueLabeledValue, VueLink, VueListBox, VueMenu, VueMeter, VueNumberField, VuePopover, VueProgressBar, VueRadio, VueRadioGroup, VueSearchField, VueSlider, VueSpectrumProvider, VueStatusLight, VueSwitch, VueTable, VueText, VueTextField, VueTree, VueUIIcon, VueView, VueWell};
export type {SpectrumContextValue} from './context';
